#import <UIKit/UIKit.h>

//! Project version number for LegacyComponents.
FOUNDATION_EXPORT double LegacyComponentsVersionNumber;

//! Project version string for LegacyComponents.
FOUNDATION_EXPORT const unsigned char LegacyComponentsVersionString[];


#import "LegacyComponentsGlobals.h"
#import "LegacyComponentsContext.h"
#import "TGLocalization.h"
#import "TGPluralization.h"
#import "TGStringUtils.h"
#import "TGPhoneUtils.h"
#import "NSObject+TGLock.h"
#import "RMPhoneFormat.h"
#import "NSInputStream+TL.h"
#import "TGFont.h"
#import "TGImageUtils.h"
#import "TGDateUtils.h"
#import "Freedom.h"
#import "FreedomUIKit.h"
#import "TGHacks.h"
#import "TGImageBlur.h"
#import "UIDevice+PlatformInfo.h"
#import "TGObserverProxy.h"
#import "TGModernCache.h"
#import "TGMemoryImageCache.h"
#import "LegacyComponentsAccessChecker.h"
#import "TGTimerTarget.h"
#import "TGKeyCommand.h"
#import "TGKeyCommandController.h"
#import "TGWeakDelegate.h"
#import "TGCache.h"
#import "TGLiveUploadInterface.h"

#import "JNWSpringAnimation.h"
#import "POPAnimationEvent.h"
#import "POPAnimationTracer.h"
#import "POPAnimation.h"
#import "POPBasicAnimation.h"
#import "POPCustomAnimation.h"
#import "POPDecayAnimation.h"
#import "POPPropertyAnimation.h"
#import "POPSpringAnimation.h"

#import "lmdb.h"
#import "PSLMDBTable.h"
#import "PSLMDBKeyValueStore.h"
#import "PSLMDBKeyValueReaderWriter.h"
#import "PSLMDBKeyValueCursor.h"

#import "PSCoding.h"
#import "PSData.h"
#import "PSKeyValueCoder.h"
#import "PSKeyValueDecoder.h"
#import "PSKeyValueEncoder.h"
#import "PSKeyValueReader.h"
#import "PSKeyValueStore.h"
#import "PSKeyValueWriter.h"

#import "TGPeerIdAdapter.h"
#import "TGUser.h"
#import "TGBotInfo.h"
#import "TGBotComandInfo.h"
#import "TGConversation.h"

#import "TGModernConversationAssociatedInputPanel.h"
#import "TGModernConversationHashtagsAssociatedPanel.h"
#import "TGModernConversationMentionsAssociatedPanel.h"
#import "TGModernConversationAlphacodeAssociatedPanel.h"
#import "TGSuggestionContext.h"
#import "TGAlphacode.h"

#import "TGTextCheckingResult.h"
#import "TGChannelBannedRights.h"
#import "TGChannelAdminRights.h"
#import "TGDatabaseMessageDraft.h"
#import "TGMessageGroup.h"
#import "TGMessageHole.h"
#import "TGMessageViewCountContentProperty.h"
#import "TGAuthorSignatureMediaAttachment.h"
#import "TGWebDocument.h"
#import "TGInvoiceMediaAttachment.h"
#import "TGGameMediaAttachment.h"
#import "TGViaUserAttachment.h"
#import "TGBotContextResultAttachment.h"
#import "TGMessageEntity.h"
#import "TGMessageEntityBold.h"
#import "TGMessageEntityBotCommand.h"
#import "TGMessageEntityCode.h"
#import "TGMessageEntityEmail.h"
#import "TGMessageEntityHashtag.h"
#import "TGMessageEntityItalic.h"
#import "TGMessageEntityMention.h"
#import "TGMessageEntityMentionName.h"
#import "TGMessageEntityPre.h"
#import "TGMessageEntityTextUrl.h"
#import "TGMessageEntityUrl.h"
#import "TGMessageEntitiesAttachment.h"
#import "TGBotReplyMarkup.h"
#import "TGBotReplyMarkupButton.h"
#import "TGBotReplyMarkupRow.h"
#import "TGReplyMarkupAttachment.h"
#import "TGInstantPage.h"
#import "TGWebPageMediaAttachment.h"
#import "TGAudioMediaAttachment.h"
#import "TGAudioWaveform.h"
#import "TGStickerPackReference.h"
#import "TGDocumentAttributeFilename.h"
#import "TGDocumentAttributeImageSize.h"
#import "TGDocumentAttributeSticker.h"
#import "TGDocumentAttributeVideo.h"
#import "TGDocumentAttributeAnimated.h"
#import "TGDocumentAttributeAudio.h"
#import "TGDocumentMediaAttachment.h"
#import "TGUnsupportedMediaAttachment.h"
#import "TGForwardedMessageMediaAttachment.h"
#import "TGContactMediaAttachment.h"
#import "TGVideoInfo.h"
#import "TGVideoMediaAttachment.h"
#import "TGLocalMessageMetaMediaAttachment.h"
#import "TGLocationMediaAttachment.h"
#import "TGImageMediaAttachment.h"
#import "TGMediaAttachment.h"
#import "TGImageInfo.h"
#import "TGMessage.h"
#import "TGStickerPack.h"
#import "TGStickerAssociation.h"
#import "TGPhotoMaskPosition.h"

#import "ActionStage.h"
#import "ASActor.h"
#import "ASHandle.h"
#import "ASQueue.h"
#import "ASWatcher.h"
#import "SGraphListNode.h"
#import "SGraphNode.h"
#import "SGraphObjectNode.h"

#import "TGLabel.h"
#import "TGToolbarButton.h"
#import "UIScrollView+TGHacks.h"
#import "TGAnimationBlockDelegate.h"
#import "TGBackdropView.h"
#import "UIImage+TG.h"
#import "TGStaticBackdropAreaData.h"
#import "TGStaticBackdropImageData.h"
#import "TGImageLuminanceMap.h"
#import "TGFullscreenContainerView.h"
#import "TGDoubleTapGestureRecognizer.h"
#import "TGModernButton.h"
#import "TGModernToolbarButton.h"
#import "TGModernBackToolbarButton.h"
#import "UIControl+HitTestEdgeInsets.h"
#import "TGMenuView.h"
#import "TGImageView.h"
#import "UICollectionView+Utils.h"
#import "TGMessageImageViewOverlayView.h"
#import "TGLetteredAvatarView.h"
#import "TGGradientLabel.h"
#import "TGRemoteImageView.h"

#import "TGProgressSpinnerView.h"
#import "TGProgressWindow.h"

#import "TGMenuSheetController.h"
#import "TGMenuSheetButtonItemView.h"
#import "TGMenuSheetCollectionView.h"
#import "TGMenuSheetItemView.h"
#import "TGMenuSheetTitleItemView.h"
#import "TGMenuSheetView.h"

#import "HPGrowingTextView.h"
#import "HPTextViewInternal.h"
#import "TGInputTextTag.h"

#import "TGStickerKeyboardTabPanel.h"

#import "TGItemPreviewController.h"
#import "TGItemPreviewView.h"
#import "TGItemMenuSheetPreviewView.h"

#import "TGImageManager.h"
#import "TGDataResource.h"
#import "TGImageDataSource.h"
#import "TGImageManagerTask.h"

#import "TGRTLScreenEdgePanGestureRecognizer.h"
#import "TGPopoverController.h"
#import "TGNavigationController.h"
#import "TGNavigationBar.h"
#import "TGViewController.h"
#import "TGViewController+TGRecursiveEnumeration.h"
#import "TGOverlayController.h"
#import "TGOverlayControllerWindow.h"

#import "TGMediaAssetsLibrary.h"
#import "TGMediaAssetsModernLibrary.h"
#import "TGMediaAsset.h"
#import "TGMediaAssetFetchResult.h"
#import "TGMediaAssetFetchResultChange.h"
#import "TGMediaAssetGroup.h"
#import "TGMediaAssetMoment.h"
#import "TGMediaAssetMomentList.h"
#import "TGMediaAssetImageSignals.h"
#import "TGMediaSelectionContext.h"
#import "TGMediaEditingContext.h"

#import "TGModernGalleryZoomableItemViewContent.h"
#import "TGModernGalleryZoomableScrollView.h"
#import "TGModernGalleryZoomableScrollViewSwipeGestureRecognizer.h"
#import "TGModernGalleryVideoView.h"
#import "TGModernGalleryScrollView.h"
#import "TGModernGalleryItem.h"
#import "TGModernGalleryItemView.h"
#import "TGModernGalleryDefaultFooterAccessoryView.h"
#import "TGModernGalleryDefaultFooterView.h"
#import "TGModernGalleryDefaultHeaderView.h"
#import "TGModernGalleryDefaultInterfaceView.h"
#import "TGModernGalleryInterfaceView.h"
#import "TGModernGalleryImageItemContainerView.h"
#import "TGModernGalleryZoomableItemView.h"
#import "TGModernGalleryModel.h"
#import "TGModernGalleryTransitionView.h"
#import "TGModernGalleryView.h"
#import "TGModernGalleryContainerView.h"
#import "TGModernGalleryEmbeddedStickersHeaderView.h"
#import "TGModernGalleryController.h"

#import "TGPhotoEditorUtils.h"
#import "PGPhotoEditorValues.h"
#import "TGVideoEditAdjustments.h"
#import "AVURLAsset+TGMediaItem.h"
#import "UIImage+TGMediaEditableItem.h"
#import "TGMediaVideoConverter.h"

#import "TGPhotoEditorAnimation.h"
#import "TGPhotoToolbarView.h"

#import "TGPaintingData.h"
#import "TGPaintUtils.h"
#import "TGPhotoPaintEntity.h"
#import "TGPhotoPaintStickerEntity.h"
#import "TGPaintUndoManager.h"

#import "PGCamera.h"
#import "PGCameraCaptureSession.h"
#import "PGCameraDeviceAngleSampler.h"
#import "PGCameraMomentSegment.h"
#import "PGCameraMomentSession.h"
#import "PGCameraMovieWriter.h"
#import "PGCameraShotMetadata.h"
#import "PGCameraVolumeButtonHandler.h"
#import "TGCameraPreviewView.h"
#import "TGCameraMainPhoneView.h"
#import "TGCameraMainTabletView.h"
#import "TGCameraMainView.h"
#import "TGCameraFlashActiveView.h"
#import "TGCameraFlashControl.h"
#import "TGCameraFlipButton.h"
#import "TGCameraInterfaceAssets.h"
#import "TGCameraModeControl.h"
#import "TGCameraSegmentsView.h"
#import "TGCameraShutterButton.h"
#import "TGCameraTimeCodeView.h"
#import "TGCameraZoomView.h"
#import "TGCameraPhotoPreviewController.h"
#import "TGCameraController.h"

#import "TGModernConversationTitleActivityIndicator.h"
#import "TGEmbedPIPButton.h"
#import "TGEmbedPIPPullArrowView.h"
#import "TGEmbedPlayerState.h"
#import "TGAttachmentCameraView.h"
#import "TGMediaAvatarMenuMixin.h"
#import "TGPasscodeEntryController.h"
#import "TGEmbedPlayerView.h"
#import "TGWallpaperInfo.h"
#import "TGMemoryImageCache.h"
#import "LegacyHTTPRequestOperation.h"
#import "LegacyComponentsAccessChecker.h"

#import "TGAttachmentCarouselItemView.h"
#import "TGMediaAssetsController.h"

#import "TGLocationMapViewController.h"
#import "TGLocationPickerController.h"
#import "TGLocationViewController.h"
#import "TGListsTableView.h"
#import "TGSearchBar.h"
#import "TGSearchDisplayMixin.h"

#import "TGPhotoEditorSliderView.h"

#import "TGClipboardGalleryMixin.h"
#import "TGClipboardGalleryPhotoItem.h"
#import "TGVideoMessageCaptureController.h"
#import "TGModernConversationInputMicButton.h"

#import "TGLocationPulseView.h"
#import "TGLocationWavesView.h"
#import "TGLocationLiveElapsedView.h"
#import "TGLocationLiveSessionItemView.h"

#import "TGTooltipView.h"
